### ISSUE TITLE
Specification on nisq benchmark adder

### ISSUE THREAD

**Issue by tbcdebug** [epiqc/ScaffCC#42]
In your nisq benchmarks, there is one called [adder](https://github.com/epiqc/ScaffCC/blob/master/nisq_benchmarks/benchmarks/adder/adder.qasm). Can you specify how this circuit is an adder? Is it the same with [this](https://www.quantum-inspire.com/kbase/full-adder/)? What are the qubits A, B, Cin, Cout?

**Comment by AndrewLitteken** [comment]
It is an adder, I can't find a resource that describes this method, but if you look [here](https://algassert.com/quirk#circuit={"cols":[["X","X",1,"H"],[1,1,"•","X"],["Z^%C2%BC","Z^%C2%BC","Z^%C2%BC","Z^-%C2%BC"],["•","X"],[1,1,"•","X"],["X",1,1,"•"],[1,"•","X"],["•","X"],[1,1,"•","X"],["Z^-%C2%BC","Z^-%C2%BC","Z^-%C2%BC","Z^%C2%BC"],["•","X"],[1,1,"•","X"],[1,1,1,"Z^%C2%BD"],["X",1,1,"•"],[1,1,1,"H"]]}) you can see the circuit, `q[0]` and `q[1]` are A and B, `q[2]` is Cin. `q[3]` is Cout.  You can treat the output of `q[2]` and `q[3]` can be treated as the result of the adder with `q[3]` as the most significant bit, and the `q[2]` as the least significant bit.

**Comment by AndrewLitteken** [comment]
The `X` at the beginning of the circuit are just initializations.
