### ISSUE TITLE
gridsynth is binary and does not work on old Linux OS

### ISSUE THREAD

**Issue by gomeztato** [epiqc/ScaffCC#5]
I am installing ScaffCC and it distributes gridsynth in binary. But it uses a newer LIBC version than I have. Source files are not available. Are they available from any other site?

**Comment by epiqc** [comment]
Yes. Our rotation generation relies on the gridsynth package by P. Selinger et al. You can find the source files on their [website](http://www.mathstat.dal.ca/~selinger/newsynth/), as cited in the compiler. We will update our documentation with instructions on installing gridsynth from source. Thank you @gomeztato for bring this up!
